"""Tests for gates.py — pre-launch per-repo gate install."""

from __future__ import annotations

import logging
import os
import stat
import subprocess
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from agent_gtd_dispatch import config, gates
from agent_gtd_dispatch.gates import (
    GATE_ENV_KEYS,
    GIT_CLIENT_HOOK_NAMES,
    LEFTHOOK_CONFIG_NAMES,
    OUTPUT_TAIL_CHARS,
    OVERRIDE_LOG_TAIL_CHARS,
    PRE_COMMIT_HOOK_TYPES,
    UNSUPPORTED_HOOK_CONFIG_NAMES,
    GateFailure,
    GateStep,
    HookManager,
    agent_shell_env,
    detect_gate_steps,
    format_failure_comment,
    format_success_lines,
    run_as_agent,
    run_gate_steps,
)


@pytest.fixture(autouse=True)
def _env(tmp_path, monkeypatch):
    """Set required env vars — mirrors the _env fixture in test_push_verification.py."""
    env = {
        "DISPATCH_API_KEY": "test-key",
        "AGENT_GTD_URL": "http://localhost:9999",
        "AGENT_GTD_API_KEY": "test-gtd-key",
        "ANTHROPIC_API_KEY": "sk-ant-test",
        "DISPATCH_WORKSPACE_ROOT": str(tmp_path),
    }
    with patch.dict(os.environ, env):
        config.load()
        yield


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


def _pre_commit_hook_body(hook_type: str, *, shim: bool = False) -> str:
    args_line = (
        f"ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type={hook_type}"
    )
    args_line += " --skip-on-missing-config)" if shim else ")"
    return (
        "#!/usr/bin/env bash\n"
        "# File generated by pre-commit: https://pre-commit.com\n"
        f"{args_line}\n"
        "INSTALL_PYTHON=/usr/bin/python3\n"
    )


LEFTHOOK_HOOK_BODY = '#!/bin/sh\ncall_lefthook run "pre-commit" "$@"\n'


def _install_pre_commit_hooks(hooks_dir: Path, *, shim: bool = False) -> None:
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for hook_type in PRE_COMMIT_HOOK_TYPES:
        (hooks_dir / hook_type).write_text(_pre_commit_hook_body(hook_type, shim=shim))


def _install_lefthook_hook(hooks_dir: Path, name: str = "pre-commit") -> None:
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / name).write_text(LEFTHOOK_HOOK_BODY)


def _install_husky_hook(
    husky_dir: Path, name: str = "pre-commit", *, executable: bool = True
) -> Path:
    husky_dir.mkdir(parents=True, exist_ok=True)
    path = husky_dir / name
    path.write_text('#!/usr/bin/env sh\n. "$(dirname "$0")/_/husky.sh"\n')
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IXUSR)
    return path


def _completed(returncode: int = 0, stdout: bytes | str = b""):
    result = MagicMock(spec=subprocess.CompletedProcess)
    result.returncode = returncode
    result.stdout = stdout
    result.stderr = b""
    return result


def _run_single_step(step: GateStep, hooks_dir_rel: str, run_id: str = "run-1"):
    """Run a single non-OVERRIDE step: install succeeds, rev-parse resolves to *hooks_dir_rel*."""
    install_result = _completed(returncode=0, stdout=b"")
    rev_result = _completed(returncode=0, stdout=hooks_dir_rel)

    def _run(argv, **_kwargs):
        if "rev-parse" in argv:
            return rev_result
        return install_result

    with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=_run):
        return run_gate_steps([step], 30, run_id=run_id)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------


class TestConstants:
    def test_git_client_hook_names(self) -> None:
        assert GIT_CLIENT_HOOK_NAMES == (
            "pre-commit",
            "pre-merge-commit",
            "prepare-commit-msg",
            "commit-msg",
            "post-commit",
            "pre-rebase",
            "post-checkout",
            "post-merge",
            "pre-push",
            "post-rewrite",
        )

    def test_lefthook_config_names(self) -> None:
        assert LEFTHOOK_CONFIG_NAMES == (
            "lefthook.yml",
            ".lefthook.yml",
            "lefthook.yaml",
            ".lefthook.yaml",
        )

    def test_pre_commit_hook_types(self) -> None:
        assert PRE_COMMIT_HOOK_TYPES == ("pre-commit", "commit-msg", "pre-push")

    def test_gate_env_keys(self) -> None:
        assert GATE_ENV_KEYS == ("PATH", "HOME", "USER", "LANG", "TERM", "SHELL")

    def test_unsupported_hook_config_names(self) -> None:
        assert UNSUPPORTED_HOOK_CONFIG_NAMES == (
            "lefthook.toml",
            ".lefthook.toml",
            "lefthook.json",
            ".lefthook.json",
            ".config/lefthook.yml",
            ".config/lefthook.yaml",
            ".githooks",
        )

    def test_output_tail_chars(self) -> None:
        assert OUTPUT_TAIL_CHARS == 1500

    def test_override_log_tail_chars(self) -> None:
        assert OVERRIDE_LOG_TAIL_CHARS == 500

    def test_hook_manager_members(self) -> None:
        assert {m.value for m in HookManager} == {
            "override",
            "lefthook",
            "pre-commit",
            "husky",
        }
        assert HookManager.OVERRIDE == "override"
        assert HookManager.LEFTHOOK == "lefthook"
        assert HookManager.PRE_COMMIT == "pre-commit"
        assert HookManager.HUSKY == "husky"


# ---------------------------------------------------------------------------
# _tail
# ---------------------------------------------------------------------------


class TestTail:
    def test_none_returns_empty(self) -> None:
        assert gates._tail(None) == ""

    def test_bytes_decoded_and_tailed(self) -> None:
        raw = ("x" * 2000).encode("ascii")
        result = gates._tail(raw)
        assert len(result) == 1500
        assert result == raw.decode("utf-8")[-1500:]

    def test_str_passthrough_tailed(self) -> None:
        raw = "y" * 2000
        result = gates._tail(raw)
        assert len(result) == 1500
        assert result == raw[-1500:]

    def test_short_input_not_padded(self) -> None:
        assert gates._tail("short") == "short"


# ---------------------------------------------------------------------------
# agent_shell_env
# ---------------------------------------------------------------------------


class TestAgentShellEnv:
    def test_filters_to_gate_env_keys_only(self, monkeypatch) -> None:
        monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-secret")
        monkeypatch.setenv("CLAUDE_CODE_OAUTH_TOKEN", "oauth-secret")
        monkeypatch.setenv("AGENT_GTD_API_KEY", "gtd-secret")
        monkeypatch.setenv("DISPATCH_API_KEY", "dispatch-secret")
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        env = agent_shell_env()
        for secret_key in (
            "ANTHROPIC_API_KEY",
            "CLAUDE_CODE_OAUTH_TOKEN",
            "AGENT_GTD_API_KEY",
            "DISPATCH_API_KEY",
        ):
            assert secret_key not in env

    def test_path_prefixed_with_local_and_cargo_bin(self, monkeypatch) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "dispatch")
        monkeypatch.setenv("PATH", "/usr/bin:/bin")
        mock_pw = MagicMock(pw_dir="/home/dispatch")
        with patch("agent_gtd_dispatch.gates.pwd.getpwnam", return_value=mock_pw):
            env = agent_shell_env()
        assert env["PATH"].startswith(
            "/home/dispatch/.local/bin:/home/dispatch/.cargo/bin:"
        )

    def test_path_absent_falls_back_to_bin_dirs_alone(self, monkeypatch) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        monkeypatch.delenv("PATH", raising=False)
        env = agent_shell_env()
        expected_prefix = str(Path.home() / ".local" / "bin")
        assert env["PATH"].startswith(expected_prefix)


# ---------------------------------------------------------------------------
# run_as_agent
# ---------------------------------------------------------------------------


class TestRunAsAgent:
    def test_success_returns_decoded_output(self, monkeypatch, tmp_path) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        completed = _completed(returncode=0, stdout=b"hello\n")
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run", return_value=completed
        ) as mock_run:
            result = run_as_agent(["/bin/bash", "-c", "echo hello"], tmp_path, 30)
        assert result.returncode == 0
        assert result.output == "hello\n"
        assert result.error is None
        assert result.duration_ms >= 0
        _, kwargs = mock_run.call_args
        assert kwargs["cwd"] == tmp_path
        assert kwargs["stdout"] == subprocess.PIPE
        assert kwargs["stderr"] == subprocess.STDOUT
        assert kwargs["timeout"] == 30
        assert kwargs["check"] is False

    def test_timeout_expired_with_output(self, monkeypatch, tmp_path) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        exc = subprocess.TimeoutExpired(cmd=["x"], timeout=5, output=b"partial output")
        with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=exc):
            result = run_as_agent(["/bin/bash", "-c", "sleep 99"], tmp_path, 5)
        assert result.returncode is None
        assert result.error == "timed out after 5s"
        assert result.output == "partial output"

    def test_timeout_expired_no_output(self, monkeypatch, tmp_path) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        exc = subprocess.TimeoutExpired(cmd=["x"], timeout=5)
        with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=exc):
            result = run_as_agent(["/bin/bash", "-c", "sleep 99"], tmp_path, 5)
        assert result.output == ""

    def test_os_error_mapped(self, monkeypatch, tmp_path) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run",
            side_effect=OSError("no such file"),
        ):
            result = run_as_agent(["/bin/bash", "-c", "x"], tmp_path, 5)
        assert result.returncode is None
        assert result.output == ""
        assert result.error == "could not start: no such file"
        assert result.duration_ms >= 0

    @pytest.mark.parametrize(
        "argv",
        [
            ["/bin/bash", "-c", "lefthook install"],
            ["/bin/bash", ".agent-gtd/setup"],
            ["git", "config", "core.hooksPath", ".husky"],
        ],
    )
    def test_argv_sudo_wrapped(self, monkeypatch, tmp_path, argv) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "dispatch")
        completed = _completed(returncode=0, stdout=b"")
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run", return_value=completed
        ) as mock_run:
            run_as_agent(argv, tmp_path, 30)
        called_argv = mock_run.call_args.args[0]
        assert called_argv == ["sudo", "-u", "dispatch", "-H", *argv]
        assert mock_run.call_args.kwargs["cwd"] == tmp_path

    def test_no_sudo_wrap_when_subprocess_user_unset(
        self, monkeypatch, tmp_path
    ) -> None:
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "")
        completed = _completed(returncode=0, stdout=b"")
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run", return_value=completed
        ) as mock_run:
            run_as_agent(["git", "config", "core.hooksPath", ".husky"], tmp_path, 30)
        called_argv = mock_run.call_args.args[0]
        assert called_argv == ["git", "config", "core.hooksPath", ".husky"]


# ---------------------------------------------------------------------------
# detect_gate_steps
# ---------------------------------------------------------------------------


class TestDetectGateSteps:
    def test_override_beats_everything(self, tmp_path, caplog) -> None:
        (tmp_path / ".agent-gtd").mkdir()
        (tmp_path / ".agent-gtd" / "setup").write_text("#!/bin/bash\nexit 0\n")
        (tmp_path / "lefthook.yml").write_text("")
        with caplog.at_level(logging.INFO):
            steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert len(steps) == 1
        step = steps[0]
        assert step.manager == HookManager.OVERRIDE
        assert step.argv == ["/bin/bash", ".agent-gtd/setup"]
        assert step.step == ".agent-gtd/setup"
        assert step.marker == ".agent-gtd/setup"
        assert step.repo_label == "repo"
        assert step.repo_path == tmp_path
        assert "decision=selected" in caplog.text
        assert "shadowed-markers" not in caplog.text

    @pytest.mark.parametrize(
        "name", ["lefthook.yml", ".lefthook.yml", "lefthook.yaml", ".lefthook.yaml"]
    )
    def test_lefthook_all_name_variants(self, tmp_path, name) -> None:
        (tmp_path / name).write_text("")
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert len(steps) == 1
        assert steps[0].manager == HookManager.LEFTHOOK
        assert steps[0].argv == ["/bin/bash", "-c", "lefthook install"]
        assert steps[0].step == "lefthook install"
        assert steps[0].marker == name

    def test_pre_commit_detected(self, tmp_path) -> None:
        (tmp_path / ".pre-commit-config.yaml").write_text("")
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert len(steps) == 1
        assert steps[0].manager == HookManager.PRE_COMMIT
        assert steps[0].argv == [
            "/bin/bash",
            "-c",
            "pre-commit install --hook-type pre-commit "
            "--hook-type commit-msg --hook-type pre-push",
        ]
        assert steps[0].marker == ".pre-commit-config.yaml"

    def test_husky_dir_detected(self, tmp_path) -> None:
        (tmp_path / ".husky").mkdir()
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert len(steps) == 1
        assert steps[0].manager == HookManager.HUSKY
        assert steps[0].argv == ["git", "config", "core.hooksPath", ".husky"]
        assert steps[0].marker == ".husky"

    def test_husky_as_file_not_detected(self, tmp_path) -> None:
        (tmp_path / ".husky").write_text("not a dir")
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert steps == []

    def test_precedence_lefthook_over_pre_commit_over_husky(self, tmp_path) -> None:
        (tmp_path / "lefthook.yml").write_text("")
        (tmp_path / ".pre-commit-config.yaml").write_text("")
        (tmp_path / ".husky").mkdir()
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert steps[0].manager == HookManager.LEFTHOOK

    def test_no_markers_no_step(self, tmp_path) -> None:
        steps = detect_gate_steps([("repo", tmp_path)], run_id="run-1")
        assert steps == []

    def test_nonexistent_path_no_step(self, tmp_path) -> None:
        steps = detect_gate_steps(
            [("repo", tmp_path / "does-not-exist")], run_id="run-1"
        )
        assert steps == []

    def test_bare_magicmock_workspace_no_step(self) -> None:
        steps = detect_gate_steps([("repo", MagicMock())], run_id="run-1")
        assert steps == []

    def test_order_follows_input_order(self, tmp_path) -> None:
        repo_a = tmp_path / "a"
        repo_a.mkdir()
        (repo_a / "lefthook.yml").write_text("")
        repo_b = tmp_path / "b"
        repo_b.mkdir()
        (repo_b / ".husky").mkdir()
        steps = detect_gate_steps([("b", repo_b), ("a", repo_a)], run_id="run-1")
        assert [s.repo_label for s in steps] == ["b", "a"]

    def test_decision_log_line_selected(self, tmp_path, caplog) -> None:
        (tmp_path / ".pre-commit-config.yaml").write_text("")
        with caplog.at_level(logging.INFO):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert (
            "gate: run_id=run-9 repo=repo manager=pre-commit "
            "marker=.pre-commit-config.yaml decision=selected"
        ) in caplog.text

    def test_decision_log_line_no_manager(self, tmp_path, caplog) -> None:
        with caplog.at_level(logging.INFO):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert (
            "gate: run_id=run-9 repo=repo manager=none marker=- decision=no-manager"
            in caplog.text
        )

    def test_shadowed_markers_warning_lefthook_selected(self, tmp_path, caplog) -> None:
        (tmp_path / "lefthook.yml").write_text("")
        (tmp_path / ".pre-commit-config.yaml").write_text("")
        with caplog.at_level(logging.WARNING):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert "decision=shadowed-markers" in caplog.text
        assert "selected=lefthook.yml" in caplog.text
        assert "ignored=.pre-commit-config.yaml" in caplog.text

    def test_no_shadowed_warning_when_single_marker(self, tmp_path, caplog) -> None:
        (tmp_path / "lefthook.yml").write_text("")
        with caplog.at_level(logging.WARNING):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert "shadowed-markers" not in caplog.text

    def test_override_never_logs_shadowed(self, tmp_path, caplog) -> None:
        (tmp_path / ".agent-gtd").mkdir()
        (tmp_path / ".agent-gtd" / "setup").write_text("exit 0\n")
        (tmp_path / "lefthook.yml").write_text("")
        (tmp_path / ".husky").mkdir()
        with caplog.at_level(logging.WARNING):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert "shadowed-markers" not in caplog.text

    def test_no_manager_unsupported_config_warning(self, tmp_path, caplog) -> None:
        (tmp_path / "lefthook.toml").write_text("")
        with caplog.at_level(logging.WARNING):
            steps = detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert steps == []
        assert "decision=no-manager-unsupported-config" in caplog.text
        assert "found=lefthook.toml" in caplog.text

    def test_no_manager_no_unsupported_no_warning(self, tmp_path, caplog) -> None:
        with caplog.at_level(logging.WARNING):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert "no-manager-unsupported-config" not in caplog.text

    def test_githooks_dir_counts_as_unsupported(self, tmp_path, caplog) -> None:
        (tmp_path / ".githooks").mkdir()
        with caplog.at_level(logging.WARNING):
            detect_gate_steps([("repo", tmp_path)], run_id="run-9")
        assert "found=.githooks" in caplog.text


# ---------------------------------------------------------------------------
# run_gate_steps — install failures / ordering
# ---------------------------------------------------------------------------


class TestRunGateStepsInstallFailures:
    def test_nonzero_exit_fails_step(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )
        result = _completed(returncode=1, stdout=b"boom output")
        with patch("agent_gtd_dispatch.gates.subprocess.run", return_value=result):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert failure.reason == "exit code 1"
        assert failure.output_tail == "boom output"
        assert failure.step == "lefthook install"
        assert failure.repo_label == "repo"
        assert failure.duration_ms >= 0

    def test_timeout_never_propagates(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run",
            side_effect=subprocess.TimeoutExpired(cmd=["x"], timeout=30),
        ):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert failure.reason == "timed out after 30s"

    def test_stop_at_first_failure(self, tmp_path) -> None:
        repo1 = tmp_path / "r1"
        repo1.mkdir()
        repo2 = tmp_path / "r2"
        repo2.mkdir()
        step1 = GateStep(
            repo_label="r1",
            repo_path=repo1,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )
        step2 = GateStep(
            repo_label="r2",
            repo_path=repo2,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )
        result = _completed(returncode=1, stdout=b"fail")
        with patch(
            "agent_gtd_dispatch.gates.subprocess.run", return_value=result
        ) as mock_run:
            failure = run_gate_steps([step1, step2], 30, run_id="run-1")
        assert failure is not None
        assert failure.repo_label == "r1"
        assert mock_run.call_count == 1


class TestRevParseFailures:
    def _step(self, repo: Path) -> GateStep:
        return GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )

    def test_nonzero_exit(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = self._step(repo)
        install_result = _completed(returncode=0, stdout=b"")
        rev_result = _completed(returncode=1, stdout="")

        def _run(argv, **_kwargs):
            return rev_result if "rev-parse" in argv else install_result

        with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=_run):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert failure.step == "hook verification (lefthook)"
        assert "exited 1" in failure.reason

    def test_timeout(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = self._step(repo)
        install_result = _completed(returncode=0, stdout=b"")

        def _run(argv, **_kwargs):
            if "rev-parse" in argv:
                raise subprocess.TimeoutExpired(cmd=argv, timeout=30)
            return install_result

        with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=_run):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert "timed out after 30s" in failure.reason

    def test_os_error(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = self._step(repo)
        install_result = _completed(returncode=0, stdout=b"")

        def _run(argv, **_kwargs):
            if "rev-parse" in argv:
                raise OSError("boom")
            return install_result

        with patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=_run):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert failure.reason == "could not resolve hooks directory: boom"


# ---------------------------------------------------------------------------
# Env on every subprocess.run call in run_gate_steps
# ---------------------------------------------------------------------------


class TestRunGateStepsEnv:
    def test_env_excludes_credentials_on_every_call(
        self, monkeypatch, tmp_path
    ) -> None:
        monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-secret")
        monkeypatch.setenv("CLAUDE_CODE_OAUTH_TOKEN", "oauth-secret")
        monkeypatch.setenv("AGENT_GTD_API_KEY", "gtd-secret")
        monkeypatch.setenv("DISPATCH_API_KEY", "dispatch-secret")
        monkeypatch.setenv("PATH", "/usr/bin:/bin")
        monkeypatch.setattr(config, "AGENT_SUBPROCESS_USER", "dispatch")
        mock_pw = MagicMock(pw_dir="/home/dispatch")

        repo = tmp_path / "repo"
        repo.mkdir()
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=["/bin/bash", "-c", "lefthook install"],
            step="lefthook install",
            marker="lefthook.yml",
        )
        install_result = _completed(returncode=0, stdout=b"")
        rev_result = _completed(returncode=0, stdout=".git/hooks")

        recorded_envs: list[dict[str, str]] = []

        def _run(argv, **kwargs):
            recorded_envs.append(kwargs.get("env"))
            return rev_result if "rev-parse" in argv else install_result

        with (
            patch("agent_gtd_dispatch.gates.pwd.getpwnam", return_value=mock_pw),
            patch("agent_gtd_dispatch.gates.subprocess.run", side_effect=_run),
        ):
            run_gate_steps([step], 30, run_id="run-1")

        assert len(recorded_envs) == 2
        for env in recorded_envs:
            for secret in (
                "ANTHROPIC_API_KEY",
                "CLAUDE_CODE_OAUTH_TOKEN",
                "AGENT_GTD_API_KEY",
                "DISPATCH_API_KEY",
            ):
                assert secret not in env
            assert env["PATH"].startswith("/home/dispatch/.local/bin:")


# ---------------------------------------------------------------------------
# Per-manager verification
# ---------------------------------------------------------------------------


class TestVerifyPreCommit:
    def test_pass_when_all_hook_types_present_and_no_skip_flag(
        self, tmp_path, caplog
    ) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        _install_pre_commit_hooks(hooks_dir, shim=False)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.PRE_COMMIT,
            argv=["/bin/bash", "-c", "pre-commit install ..."],
            step="pre-commit install ...",
            marker=".pre-commit-config.yaml",
        )
        with caplog.at_level(logging.INFO):
            failure = _run_single_step(step, ".git/hooks")
        assert failure is None
        assert "decision=installed-verified" in caplog.text
        assert "manager=pre-commit" in caplog.text
        assert "verified_hooks=pre-commit,commit-msg,pre-push" in caplog.text

    def test_fails_when_shim_flag_present(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        _install_pre_commit_hooks(hooks_dir, shim=True)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.PRE_COMMIT,
            argv=[],
            step="pre-commit install",
            marker=".pre-commit-config.yaml",
        )
        failure = _run_single_step(step, ".git/hooks")
        assert failure is not None
        assert failure.step == "hook verification (pre-commit)"
        assert (
            failure.reason
            == f"pre-commit in {hooks_dir} is not a pre-commit-installed hook"
        )

    def test_fails_when_hook_missing_names_first_offender(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        (hooks_dir / "pre-commit").write_text(_pre_commit_hook_body("pre-commit"))
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.PRE_COMMIT,
            argv=[],
            step="x",
            marker="y",
        )
        failure = _run_single_step(step, ".git/hooks")
        assert failure is not None
        assert "commit-msg in" in failure.reason


class TestVerifyLefthook:
    def test_pass_when_hook_contains_lefthook_marker(self, tmp_path, caplog) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        _install_lefthook_hook(hooks_dir, "pre-commit")
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=[],
            step="lefthook install",
            marker="lefthook.yml",
        )
        with caplog.at_level(logging.INFO):
            failure = _run_single_step(step, ".git/hooks")
        assert failure is None
        assert "verified_hooks=pre-commit" in caplog.text

    def test_old_backup_does_not_count(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        (hooks_dir / "pre-commit.old").write_text(LEFTHOOK_HOOK_BODY)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=[],
            step="x",
            marker="y",
        )
        failure = _run_single_step(step, ".git/hooks")
        assert failure is not None
        assert failure.reason == f"no lefthook-managed hook found in {hooks_dir}"

    def test_pre_commit_shim_does_not_count(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        (hooks_dir / "pre-commit").write_text(
            _pre_commit_hook_body("pre-commit", shim=True)
        )
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=[],
            step="x",
            marker="y",
        )
        failure = _run_single_step(step, ".git/hooks")
        assert failure is not None


class TestVerifyHusky:
    def test_pass_when_hooks_path_resolves_to_husky_and_executable(
        self, tmp_path, caplog
    ) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        husky_dir = repo / ".husky"
        _install_husky_hook(husky_dir, "pre-commit", executable=True)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.HUSKY,
            argv=[],
            step="git config core.hooksPath .husky",
            marker=".husky",
        )
        with caplog.at_level(logging.INFO):
            failure = _run_single_step(step, ".husky")
        assert failure is None
        assert "manager=husky" in caplog.text
        assert "verified_hooks=pre-commit" in caplog.text

    def test_fails_when_hooks_path_not_husky(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        husky_dir = repo / ".husky"
        _install_husky_hook(husky_dir)
        (repo / ".git" / "hooks").mkdir(parents=True)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.HUSKY,
            argv=[],
            step="x",
            marker="y",
        )
        failure = _run_single_step(step, ".git/hooks")
        assert failure is not None
        assert "expected .husky" in failure.reason

    def test_fails_when_no_executable_hook(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        husky_dir = repo / ".husky"
        _install_husky_hook(husky_dir, executable=False)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.HUSKY,
            argv=[],
            step="x",
            marker="y",
        )
        failure = _run_single_step(step, ".husky")
        assert failure is not None
        assert failure.reason == "no executable hook script found in .husky/"


class TestVerificationOSError:
    def test_os_error_while_reading_hook_fails_step(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        hooks_dir = repo / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        (hooks_dir / "pre-commit").write_text(LEFTHOOK_HOOK_BODY)
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.LEFTHOOK,
            argv=[],
            step="x",
            marker="y",
        )

        real_read_bytes = Path.read_bytes

        def _bad_read_bytes(self: Path):
            if self.name == "pre-commit":
                raise OSError("permission denied")
            return real_read_bytes(self)

        with patch.object(Path, "read_bytes", _bad_read_bytes):
            failure = _run_single_step(step, ".git/hooks")
        assert failure is not None
        assert "could not read" in failure.reason
        assert "permission denied" in failure.reason


# ---------------------------------------------------------------------------
# OVERRIDE step
# ---------------------------------------------------------------------------


class TestOverrideStep:
    def test_success_no_verification_single_subprocess_call(
        self, tmp_path, caplog
    ) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.OVERRIDE,
            argv=["/bin/bash", ".agent-gtd/setup"],
            step=".agent-gtd/setup",
            marker=".agent-gtd/setup",
        )
        result = _completed(returncode=0, stdout=b"setup output" * 100)
        with (
            caplog.at_level(logging.INFO),
            patch(
                "agent_gtd_dispatch.gates.subprocess.run", return_value=result
            ) as mock_run,
        ):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is None
        assert mock_run.call_count == 1
        assert "decision=override-ok" in caplog.text
        assert "manager=override" in caplog.text

    def test_failure_still_mapped(self, tmp_path) -> None:
        repo = tmp_path / "repo"
        repo.mkdir()
        step = GateStep(
            repo_label="repo",
            repo_path=repo,
            manager=HookManager.OVERRIDE,
            argv=["/bin/bash", ".agent-gtd/setup"],
            step=".agent-gtd/setup",
            marker=".agent-gtd/setup",
        )
        result = _completed(returncode=1, stdout=b"setup failed")
        with patch("agent_gtd_dispatch.gates.subprocess.run", return_value=result):
            failure = run_gate_steps([step], 30, run_id="run-1")
        assert failure is not None
        assert failure.reason == "exit code 1"


# ---------------------------------------------------------------------------
# Comment formatting
# ---------------------------------------------------------------------------


class TestFormatFailureComment:
    def test_with_output_tail(self) -> None:
        failure = GateFailure(
            repo_label="repo",
            step="lefthook install",
            reason="exit code 1",
            output_tail="boom",
            duration_ms=100,
        )
        result = format_failure_comment("run-1", failure)
        expected = (
            "Gate install failed before the agent launched (run `run-1`). "
            "The agent was not started.\n\n"
            "- Repo: `repo`\n"
            "- Step: `lefthook install`\n"
            "- Result: exit code 1"
            "\n\n```\nboom\n```"
        )
        assert result == expected

    def test_without_output_tail(self) -> None:
        failure = GateFailure(
            repo_label="repo",
            step="lefthook install",
            reason="exit code 1",
            output_tail="",
            duration_ms=100,
        )
        result = format_failure_comment("run-1", failure)
        expected = (
            "Gate install failed before the agent launched (run `run-1`). "
            "The agent was not started.\n\n"
            "- Repo: `repo`\n"
            "- Step: `lefthook install`\n"
            "- Result: exit code 1"
        )
        assert result == expected
        assert not result.endswith("\n")


class TestFormatSuccessLines:
    def test_empty_list(self) -> None:
        assert format_success_lines([]) == ""

    def test_mixed_managers(self, tmp_path) -> None:
        steps = [
            GateStep(
                repo_label="a",
                repo_path=tmp_path,
                manager=HookManager.LEFTHOOK,
                argv=[],
                step="x",
                marker="y",
            ),
            GateStep(
                repo_label="b",
                repo_path=tmp_path,
                manager=HookManager.OVERRIDE,
                argv=[],
                step="x",
                marker="y",
            ),
        ]
        result = format_success_lines(steps)
        assert result == (
            "\nGit hooks: `a` lefthook — verified"
            "\nGit hooks: `b` override — override ran (unverified)"
        )


# ---------------------------------------------------------------------------
# config.GATE_INSTALL_TIMEOUT_SECONDS
# ---------------------------------------------------------------------------


class TestGateInstallTimeoutConfig:
    def test_default(self, tmp_path) -> None:
        env = {
            "DISPATCH_API_KEY": "test-key",
            "AGENT_GTD_URL": "http://localhost:9999",
            "AGENT_GTD_API_KEY": "test-gtd-key",
            "ANTHROPIC_API_KEY": "sk-ant-test",
            "DISPATCH_WORKSPACE_ROOT": str(tmp_path),
        }
        with patch.dict(os.environ, env, clear=False):
            os.environ.pop("DISPATCH_GATE_INSTALL_TIMEOUT_SECONDS", None)
            config.load()
        assert config.GATE_INSTALL_TIMEOUT_SECONDS == 300

    def test_env_override(self, tmp_path) -> None:
        env = {
            "DISPATCH_API_KEY": "test-key",
            "AGENT_GTD_URL": "http://localhost:9999",
            "AGENT_GTD_API_KEY": "test-gtd-key",
            "ANTHROPIC_API_KEY": "sk-ant-test",
            "DISPATCH_WORKSPACE_ROOT": str(tmp_path),
            "DISPATCH_GATE_INSTALL_TIMEOUT_SECONDS": "45",
        }
        with patch.dict(os.environ, env):
            config.load()
        assert config.GATE_INSTALL_TIMEOUT_SECONDS == 45


# ---------------------------------------------------------------------------
# Worker-level integration (main._dispatch_worker gate block)
# ---------------------------------------------------------------------------


class TestWorkerGateIntegration:
    @pytest.mark.asyncio
    async def test_build_gate_failure_fails_run_before_launch(
        self, tmp_path, caplog
    ) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-gate-1",
            project_name="TestProject",
            branch_name="feat/gate-fail",
            mode=DispatchMode.BUILD,
        )
        await db.insert_run(run)

        (tmp_path / ".pre-commit-config.yaml").write_text("")

        failure = GateFailure(
            repo_label="repo",
            step="pre-commit install",
            reason="exit code 1",
            output_tail="boom output",
            duration_ms=42,
        )

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch(
                "agent_gtd_dispatch.main.gates.run_gate_steps", return_value=failure
            ) as mock_run_gate_steps,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-gate-1",
                    "title": "Fix bug",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace = MagicMock(return_value=tmp_path)
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaabc")
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")
            mock_dispatch.run_agent = AsyncMock()
            mock_dispatch.verify_pushes = MagicMock(return_value=[])
            mock_dispatch.cleanup_workspace = MagicMock()
            mock_dispatch._executor = None

            with caplog.at_level(logging.INFO):
                await _dispatch_worker(run, 50, CLAUDE, 600)

        updated = await db.get_run(run.id)
        assert updated is not None
        assert updated.status.value == "failed"
        assert updated.error is not None
        assert (
            "gate install failed: repo: pre-commit install: exit code 1"
            in updated.error
        )

        mock_run_gate_steps.assert_called_once()
        args, kwargs = mock_run_gate_steps.call_args
        assert args[0][0].manager == HookManager.PRE_COMMIT
        assert args[1] == 300
        assert kwargs["run_id"] == run.id

        mock_dispatch.build_system_prompt.assert_not_called()
        mock_dispatch.run_agent.assert_not_called()

        assert mock_gtd.post_comment.await_count == 1
        posted_body = mock_gtd.post_comment.call_args.args[1]
        assert posted_body.startswith("Gate install failed before the agent launched")

        mock_dispatch.cleanup_workspace.assert_called_once_with(tmp_path)
        assert "decision=failed" in caplog.text

    @pytest.mark.asyncio
    async def test_build_gate_success_appends_comment_and_launches(
        self, tmp_path
    ) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-gate-2",
            project_name="TestProject",
            branch_name="feat/gate-ok",
            mode=DispatchMode.BUILD,
        )
        await db.insert_run(run)

        (tmp_path / ".pre-commit-config.yaml").write_text("")

        completed_result = MagicMock()
        completed_result.returncode = 0

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch(
                "agent_gtd_dispatch.main.gates.run_gate_steps", return_value=None
            ) as mock_run_gate_steps,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-gate-2",
                    "title": "Fix bug",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace = MagicMock(return_value=tmp_path)
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaabc")
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")
            mock_dispatch.run_agent = AsyncMock(return_value=completed_result)
            mock_dispatch.verify_pushes = MagicMock(return_value=[])
            mock_dispatch.cleanup_workspace = MagicMock()
            mock_dispatch._executor = None

            await _dispatch_worker(run, 50, CLAUDE, 600)

        mock_run_gate_steps.assert_called_once()
        args, kwargs = mock_run_gate_steps.call_args
        assert args[0][0].manager == HookManager.PRE_COMMIT
        assert args[1] == 300
        assert kwargs["run_id"] == run.id

        dispatch_comment_calls = [
            c.args[1] for c in mock_gtd.post_comment.call_args_list if len(c.args) > 1
        ]
        assert any(
            "Git hooks: `repo` pre-commit — verified" in body
            for body in dispatch_comment_calls
        )
        mock_dispatch.run_agent.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_no_manager_path_skips_executor(self, tmp_path) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-gate-3",
            project_name="TestProject",
            branch_name="feat/no-manager",
            mode=DispatchMode.BUILD,
        )
        await db.insert_run(run)

        completed_result = MagicMock()
        completed_result.returncode = 0

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch(
                "agent_gtd_dispatch.main.gates.run_gate_steps"
            ) as mock_run_gate_steps,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-gate-3",
                    "title": "Fix bug",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace = MagicMock(return_value=tmp_path)
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaabc")
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")
            mock_dispatch.run_agent = AsyncMock(return_value=completed_result)
            mock_dispatch.verify_pushes = MagicMock(return_value=[])
            mock_dispatch.cleanup_workspace = MagicMock()
            mock_dispatch._executor = "SENTINEL-UNTOUCHED"

            await _dispatch_worker(run, 50, CLAUDE, 600)

        mock_run_gate_steps.assert_not_called()
        mock_dispatch.run_agent.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_talos_engine_skips_gate(self, tmp_path, caplog) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import TALOS_HAIKU
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-talos-1",
            project_name="TestProject",
            branch_name="feat/talos",
            mode=DispatchMode.BUILD,
            engine="talos-haiku",
        )
        await db.insert_run(run)

        (tmp_path / ".pre-commit-config.yaml").write_text("")

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch("agent_gtd_dispatch.main.gates") as mock_gates,
            patch(
                "agent_gtd_dispatch.main._run_talos", new_callable=AsyncMock
            ) as mock_run_talos,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-talos-1",
                    "title": "Fix bug",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace = MagicMock(return_value=tmp_path)
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaabc")
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")

            with caplog.at_level(logging.INFO):
                await _dispatch_worker(run, 50, TALOS_HAIKU, 600)

        mock_gates.detect_gate_steps.assert_not_called()
        mock_run_talos.assert_awaited_once()
        assert "decision=skipped reason=talos" in caplog.text

        import subprocess as _subprocess_mod

        talos_diff = _subprocess_mod.run(
            ["git", "diff", "--name-only", "src/agent_gtd_dispatch/talos.py"],
            capture_output=True,
            text=True,
            check=False,
            cwd=Path(__file__).resolve().parent.parent,
        )
        assert talos_diff.stdout.strip() == ""

    @pytest.mark.asyncio
    async def test_plan_mode_skips_gate(self, tmp_path, caplog) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-plan-1",
            project_name="TestProject",
            branch_name=None,
            mode=DispatchMode.PLAN,
        )
        await db.insert_run(run)

        (tmp_path / "lefthook.yml").write_text("")

        completed_result = MagicMock()
        completed_result.returncode = 0

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch("agent_gtd_dispatch.main.gates") as mock_gates,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-plan-1",
                    "title": "Plan feature",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace = MagicMock(return_value=tmp_path)
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaxyz")
            mock_dispatch.repo_name_from_origin = MagicMock(
                return_value="repos-testproj"
            )
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")
            mock_dispatch.run_agent = AsyncMock(return_value=completed_result)
            mock_dispatch.verify_pushes = MagicMock(return_value=[])
            mock_dispatch.cleanup_workspace = MagicMock()

            with caplog.at_level(logging.INFO):
                await _dispatch_worker(run, 50, CLAUDE, 600)

        mock_gates.detect_gate_steps.assert_not_called()
        assert "decision=skipped reason=plan" in caplog.text

    @pytest.mark.asyncio
    async def test_workspace_mode_gates_only_matching_repo(self, tmp_path) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            item_id="item-ws-1",
            project_name="TestProject",
            branch_name="feat/ws",
            mode=DispatchMode.BUILD,
        )
        await db.insert_run(run)

        (tmp_path / "agent-gtd-dispatch").mkdir()
        (tmp_path / "agent-gtd-dispatch" / "lefthook.yml").write_text("")

        completed_result = MagicMock()
        completed_result.returncode = 0

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch(
                "agent_gtd_dispatch.main.gates.run_gate_steps", return_value=None
            ) as mock_run_gate_steps,
        ):
            mock_gtd.get_item = AsyncMock(
                return_value={
                    "id": "item-ws-1",
                    "title": "Fix bug",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "repo_mode": "workspace",
                    "workspace_repos": [
                        "git@ubuntu-vm01:repos/agent_gtd",
                        "git@ubuntu-vm01:repos/agent-gtd-dispatch",
                    ],
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.list_attachments = AsyncMock(return_value=[])

            mock_dispatch.prepare_workspace_multi.return_value = tmp_path
            mock_dispatch.repo_dir_from_url.side_effect = lambda u: (
                u.rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")
            )
            mock_dispatch.get_head_sha = MagicMock(return_value="baseshaabc")
            mock_dispatch.stage_attachments = AsyncMock(return_value=[])
            mock_dispatch.build_system_prompt = MagicMock(return_value="prompt text")
            mock_dispatch.run_agent = AsyncMock(return_value=completed_result)
            mock_dispatch.verify_pushes = MagicMock(return_value=[])
            mock_dispatch.cleanup_workspace = MagicMock()
            mock_dispatch._executor = None

            await _dispatch_worker(run, 50, CLAUDE, 600)

        mock_run_gate_steps.assert_called_once()
        args, _kwargs = mock_run_gate_steps.call_args
        steps = args[0]
        assert len(steps) == 1
        assert steps[0].repo_label == "agent-gtd-dispatch"
        assert steps[0].manager == HookManager.LEFTHOOK

        mock_dispatch.run_agent.assert_awaited_once()


class TestWorkerGateManageHalt:
    @pytest.mark.asyncio
    async def test_manage_gate_failure_halts_rollout(self, tmp_path) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            project_name="TestProject",
            mode=DispatchMode.MANAGE,
            rollout_id="rollout-1",
            callback_token="cb-token",
        )
        await db.insert_run(run)

        (tmp_path / "lefthook.yml").write_text("")

        failure = GateFailure(
            repo_label="repo",
            step="lefthook install",
            reason="exit code 1",
            output_tail="boom output",
            duration_ms=10,
        )

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch("agent_gtd_dispatch.main.gates.run_gate_steps", return_value=failure),
        ):
            mock_gtd.get_rollout = AsyncMock(
                return_value={
                    "id": "rollout-1",
                    "status": "halted",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.halt_rollout = AsyncMock()
            mock_gtd.relaunch_manage_rollout = AsyncMock()

            mock_dispatch.prepare_manage_workspace.return_value = tmp_path
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch._executor = None
            mock_dispatch.cleanup_workspace = MagicMock()

            await _dispatch_worker(run, 50, CLAUDE, 600)

        mock_gtd.halt_rollout.assert_awaited_once()
        _, kwargs = mock_gtd.halt_rollout.call_args
        assert kwargs["token"] == "cb-token"  # noqa: S105
        assert "```\nboom output\n```" in kwargs["comment"]
        assert (
            "gate install failed in repo: lefthook install: exit code 1"
            in kwargs["reason"]
        )

        mock_gtd.relaunch_manage_rollout.assert_not_called()
        mock_dispatch.cleanup_workspace.assert_called_once_with(tmp_path)

    @pytest.mark.asyncio
    async def test_manage_gate_failure_halt_retries_with_static_token(
        self, tmp_path
    ) -> None:
        from agent_gtd_dispatch import db
        from agent_gtd_dispatch.engines import CLAUDE
        from agent_gtd_dispatch.main import _dispatch_worker
        from agent_gtd_dispatch.models import DispatchMode, Run

        await db.init_db()
        run = Run(
            project_name="TestProject",
            mode=DispatchMode.MANAGE,
            rollout_id="rollout-2",
            callback_token="cb-token",
        )
        await db.insert_run(run)

        (tmp_path / "lefthook.yml").write_text("")

        failure = GateFailure(
            repo_label="repo",
            step="lefthook install",
            reason="exit code 1",
            output_tail="boom",
            duration_ms=10,
        )

        with (
            patch("agent_gtd_dispatch.main.gtd_client") as mock_gtd,
            patch("agent_gtd_dispatch.main.dispatch") as mock_dispatch,
            patch("agent_gtd_dispatch.main.gates.run_gate_steps", return_value=failure),
        ):
            mock_gtd.get_rollout = AsyncMock(
                return_value={
                    "id": "rollout-2",
                    "status": "halted",
                    "project_id": "proj1",
                }
            )
            mock_gtd.get_project = AsyncMock(
                return_value={
                    "id": "proj1",
                    "name": "TestProject",
                    "git_origin": "git@host:repos/testproj",
                }
            )
            mock_gtd.post_comment = AsyncMock()
            mock_gtd.halt_rollout = AsyncMock(
                side_effect=[Exception("boom-halt"), None]
            )

            mock_dispatch.prepare_manage_workspace.return_value = tmp_path
            mock_dispatch.repo_name_from_origin = MagicMock(return_value="repo")
            mock_dispatch._executor = None
            mock_dispatch.cleanup_workspace = MagicMock()

            await _dispatch_worker(run, 50, CLAUDE, 600)

        assert mock_gtd.halt_rollout.await_count == 2
        first_call, second_call = mock_gtd.halt_rollout.call_args_list
        assert first_call.kwargs["token"] == "cb-token"  # noqa: S105
        assert second_call.kwargs["token"] is None
